export const adminCompanyFields = [
  "id",
  "name",
  "email",
  "phone",
  "address",
  "city",
  "state",
  "zip",
  "country",
  "logo_url",
  "currency_code",
  "status",
  "welcome_code",
  "price_list_id",
  "invoice_payment_enabled",
  "created_at",
  "employees.id",
  "employees.role",
  "employees.spending_limit",
  "employees.location.id",
  "employees.location.name",
  "employees.customer.id",
  "employees.customer.email",
  "employees.customer.first_name",
  "employees.customer.last_name",
  "locations.id",
  "locations.name",
  "locations.address_1",
  "locations.address_2",
  "locations.city",
  "locations.state",
  "locations.zip",
  "locations.phone",
];

export const adminCompanyQueryConfig = {
  list: { defaults: adminCompanyFields, isList: true },
  retrieve: { defaults: adminCompanyFields, isList: false },
};
